import { Link } from 'react-router-dom';
import Navbar from './Navbar';
import Footer from './Footer';
import styles from './NotFoundPage.module.css';
import { useDocumentMeta } from '../lib/useDocumentMeta';

// Client-side catch-all for any unmatched route (bad /learn/:slug,
// /areas/:slug, or a stray path). The server-side counterpart is
// dist/404.html, generated by scripts/prerender.mjs and served with a real
// HTTP 404 via public/_redirects — this component is what a JS-enabled
// visitor sees either way (a direct hit on the static file, or a client-
// side navigation to a bad in-app link).
export default function NotFoundPage() {
  useDocumentMeta('Page Not Found | Wraptors Dubai', "The page you're looking for doesn't exist — here's where to go instead.");

  return (
    <>
      <Navbar alwaysVisible />
      <main className={styles.main}>
        <span className={styles.code}>404</span>
        <h1 className={styles.headline}>Page Not Found</h1>
        <p className={styles.sub}>
          That page doesn&rsquo;t exist — it may have moved, or the link was mistyped.
        </p>
        <div className={styles.actions}>
          <Link to="/" className={styles.primary}>Back to Home</Link>
          <Link to="/learn" className={styles.secondary}>Browse Insights</Link>
          <Link to="/#services" className={styles.secondary}>View Services</Link>
        </div>
      </main>
      <Footer />
    </>
  );
}
